server.port=8080

spring.application.name=api-gateway

# Route mapping to internal/external microservices
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8085}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=ticket-service
spring.cloud.gateway.routes[1].uri=http://${TICKET_SERVICE_HOST:localhost}:${TICKET_SERVICE_PORT:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/tickets/**

spring.cloud.gateway.routes[2].id=comment-service
spring.cloud.gateway.routes[2].uri=http://${COMMENT_SERVICE_HOST:localhost}:${COMMENT_SERVICE_PORT:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/comments/**

spring.cloud.gateway.routes[3].id=attachment-service
spring.cloud.gateway.routes[3].uri=http://${ATTACHMENT_SERVICE_HOST:localhost}:${ATTACHMENT_SERVICE_PORT:8084}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/attachments/**

# Global CORS Configuration for Gateway
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

# Deduplicate headers to avoid browser blocks if downstream microservices send duplicate headers
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_LAST
